channels:
- conda-forge
dependencies:
- python=3.10.13
- pip<=23.0.1
- pip:
  - mlflow==3.6.0
  - cloudpickle==3.1.2
  - numpy==2.0.2
  - pandas==2.3.3
  - psutil==7.1.3
  - pyarrow==22.0.0
  - scikit-learn==1.7.2
  - scipy==1.15.3
name: mlflow-env
